### ISSUE TITLE
repo now online

### ISSUE THREAD

**Issue by burghy86** [szyb/synopackage_dotnet#236]
https://www.hofrichter.at/sspks/ is return online

https://packages.jdel.org/ are online but is empy

**Comment by szyb** [comment]
Thanks @burghy86 ! 
Just checked. Hofrichter is back online. I will return it to active list.
Jdel is empty on the website. For DSM returns error (Bad Gateway), so it will stay as inactive.

**Comment by szyb** [comment]
By the way I updated sources list.
Hofrichter is now active.
Page81, Emby & Beatificabytes are moved to inactive. Emby is not a valid repo for DSM, but they still have packages available on their website
